[tool.poetry]
name = "bot"
version = "0.1.0"
description = "VK Bot for testing system"
authors = ["Paskera <craftsun@yandex.ru>"]
readme = "README.md"
packages = [
    { include = "bot", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.10"
vk-api = "^11.10.0"
pymysql = "^1.1.2"
cryptography = "^46.0.3"
sqlalchemy = "^2.0.44"
dotenv = "^0.9.9"
psycopg2-binary = "^2.9.11"

[tool.poetry.scripts]
dev = "src.bot.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"